mr_robot_firmware :
  motor_rpm : 100  
  wheel_diameter : 0.115
  wheel_separation : 0.24
  max_pwm_val : 300 
  min_pwm_val : 50
  twist_max_pwm : 210
  twist_min_pwm : -210
  leftA : 12
  leftB : 18
  rightA : 13
  rightB : 6
  rate : 10.0
  ticks_meter : 6550
  base_width : 0.20
  base_frame_id : 'base_link'
  odom_frame_id : 'odom'
  # encoder_min : -2147483648
  # encoder_max : 2147483648
